# Site settings
title: "幸福在路上"
url: "//windmissing.github.io"
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
author:
    name: windmissing
    github: windmissing
    email: windmissinghe@gmail.com
    gitcafe:
    twitter: WindmissingHe
    facebook:
    googleplus:
    weibo:
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: kramdown
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
permalink: /:categories/:year-:month/:title.html

assets_path: /assets
sass:
    sass_dir: assets/_sass
    style: :compressed

# comment
comments:
    duoshuo:
        name: windmissing                              # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26

# tinysou.com
search:
    tinysou:
        engineKey: 

# 网站统计
analytics:
    liangzi : 3608735                             # 百度统
